services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  server:
    build:
      context: .
      target: final
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiM2RiMWFmZjlhYWIxYjZlMDA3MmM4MTRjMDNjMGY3MzgiLCJ0IjoiNzZhYWY3MjEtMWEzMy00N2I0LWIwYWYtMjlhNjg4MDYwY2VhIiwicyI6Ik5UUXpaRGs1WWpNdFlXUXdaUzAwTkdSaExUaGtNMll0WVRjMFl6ZGhOVFkxWW1GaiJ9
    depends_on:
      - nginx

volumes:
  postgres_data:
